- name: "Deploy Application"
  hosts: all
  become: true
  tasks:
    - name: "Make /opt/freedome/uploads"
      ansible.builtin.file:
        path: /opt/freedome
        state: directory
        mode: 0755

    - name: "Make /opt/freedome/uploads"
      ansible.builtin.file:
        path: /opt/freedome/uploads
        state: directory
        mode: 0755
        
    - name: "Allow all access to tcp port {{ item }}"
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop: 
        - 443
        - 80
  
    - name: Run migrations
      community.docker.docker_container:
        name: "{{ image_name }}"
        state: started
        recreate: true
        image: "{{ repository_url }}/{{ image_name }}:{{ image_tag }}"
        pull: true
        entrypoint: ["python", "manage.py", "migrate"]
        env:
          DB_NAME: "{{ db_name }}"
          DB_USER: "{{ db_user }}"
          DB_PASSWORD: "{{ db_password }}"
          DB_HOST: "{{ db_host }}"
          DB_PORT: "{{ db_port }}"
          ALLOWED_HOSTS_URL: "{{ allowed_hosts_url }}"
          SECRET_KEY: "{{ secret_key }}"
          DJANGO_SETTINGS_MODULE: "{{ django_settings_module }}"
          TRUSTED_ORIGIN_URL: "{{ trusted_origin_url }}"

    - name: Start Application Container
      community.docker.docker_container:
        name: "{{ image_name }}"
        state: started
        recreate: true
        image: "{{ repository_url }}/{{ image_name }}:{{ image_tag }}"
        ports:
        - "8000:8000"
        mounts:
          target: uploads
          source: /opt/freedome/uploads
        env:
          DB_NAME: "{{ db_name }}"
          DB_USER: "{{ db_user }}"
          DB_PASSWORD: "{{ db_password }}"
          DB_HOST: "{{ db_host }}"
          DB_PORT: "{{ db_port }}"
          ALLOWED_HOSTS_URL: "{{ allowed_hosts_url }}"
          SECRET_KEY: "{{ secret_key }}"
          DJANGO_SETTINGS_MODULE: "{{ django_settings_module }}"
          TRUSTED_ORIGIN_URL: "{{ trusted_origin_url }}"

